name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21]
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
      
    - name: Build
      run: |
        env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }}
        
    - name: Package
      run: |
        tar -czvf ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }}.tar.gz ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }}
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }}
        path: ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest 
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}_linux_amd64.tar.gz
            ${{ github.event.repository.name }}_linux_arm64.tar.gz
            ${{ github.event.repository.name }}_windows_amd64.tar.gz 
            ${{ github.event.repository.name }}_windows_arm64.tar.gz
            ${{ github.event.repository.name }}_darwin_amd64.tar.gz
            ${{ github.event.repository.name }}_darwin_arm64.tar.gz
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
