name: Release Go project

on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      run: |  
        go get github.com/mitchellh/gox
        gox -os="linux darwin windows" -arch="amd64 arm64" -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}_${GITHUB_REF##*/}"
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/*