name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21]
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      
    - name: Build
      run: |
        env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }}
        
    - name: Build and Package
      run: |
       FILE_NAME="${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }}_${{ github.ref_name }}.tar.gz"
       env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o $FILE_NAME
       tar -czvf $FILE_NAME $FILE_NAME
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
      name: $FILE_NAME
      path: ${{ github.workspace }}/$FILE_NAME

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            ${{ github.event.repository.name }}_linux_amd64_${GITHUB_REF_NAME}.tar.gz
            ${{ github.event.repository.name }}_linux_arm64_${GITHUB_REF_NAME}.tar.gz
            ${{ github.event.repository.name }}_windows_amd64_${GITHUB_REF_NAME}.tar.gz
            ${{ github.event.repository.name }}_windows_arm64_${GITHUB_REF_NAME}.tar.gz
            ${{ github.event.repository.name }}_darwin_amd64_${GITHUB_REF_NAME}.tar.gz
            ${{ github.event.repository.name }}_darwin_arm64_${GITHUB_REF_NAME}.tar.gz
